#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  echo -e "No arguments specified";
  exit 1;
fi

if ! [ -x "$(command -v avrdude)" ]; then
  echo "You must install avrdude first"
fi

if ! [ -f /etc/udev/rules.d/99-arduboy.rules ]; then
  echo "Adding Arduboy rules to /etc/udev/rules.d/99-arduboy.rules"

  echo 'ACTION=="add", ATTRS{idVendor}=="2341", ATTRS{idProduct}=="0036", SYMLINK+="arduboy-boot", MODE="0666"' | sudo tee /etc/udev/rules.d/99-arduboy.rules
  echo 'ACTION=="add", ATTRS{idVendor}=="2341", ATTRS{idProduct}=="8036", SYMLINK+="arduboy", MODE="0666"' | sudo tee -a /etc/udev/rules.d/99-arduboy.rules
fi

if [ "$(id -Gn "$USER" | grep -c "dialout")" -eq 0 ]; then
  echo "Adding ${USER} to dialout group"

  sudo usermod -a -G dialout "$USER"
fi

echo -e 'Searching for Arduboy...'

while [ ! -e /dev/arduboy-boot ]; do
  if [ -e /dev/arduboy ]; then
    echo -e 'Arduboy found. Trying to reset.'

    stty -F /dev/arduboy ispeed 1200 ospeed 1200

    while [ -e /dev/arduboy ]; do
      sleep 0.1
    done;
  fi

  sleep 0.1
done

avrdude -v -patmega32u4 -cavr109 -P/dev/arduboy-boot -b57600 -D -Uflash:w:"$1":i
